name: CI

on: [push]

jobs:
  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12, 13]
        # Windows (windows-latest) doesn't work with karma
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build
        npm run test

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: publish release package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
          npm i
          npm run build
          npm publish
        if: contains( github.ref, 'master' ) || contains( github.base_ref, 'master' )

      - name: publish preview package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          CURRENT_TIME=$(date +%s)
          NEW_VERSION=${PACKAGE_VERSION}-build${CURRENT_TIME}
          npm i
          npm run build
          npm version $NEW_VERSION --no-git-tag-version
          npm publish  --tag next
        if: contains( github.ref, 'develop' ) || contains( github.base_ref, 'develop' )
